name: Build Analytical

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Set up uv
      uses: astral-sh/setup-uv@v7
      with:
        version: "0.11.28"
        enable-cache: true

    - name: Install System Dependencies
      run: sudo apt-get update && sudo apt-get install --yes --no-install-recommends gcc g++ make cmake libboost-dev libboost-program-options-dev libprotobuf-dev protobuf-compiler

    - name: Synchronize Python environment
      run: ${{github.workspace}}/utils/setup.sh
        
    - name: Build
      run: bash ${{github.workspace}}/build/astra_analytical/build.sh

